[functions]
  external_node_modules = ["express", "xml2js"]
  node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force=true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  functions = "functions/api"
